# Generated by Django 5.1.1 on 2024-10-12 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('formateur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=15, unique=True)),
                ('adresse', models.TextField()),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('role', models.CharField(choices=[('agriculteur', 'Agriculteur'), ('partenaire', 'Partenaire'), ('administrateur', 'Administrateur')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('progression', models.FloatField(default=0.0)),
                ('score_quiz', models.FloatField(default=0.0)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='Gestions.formation')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='Gestions.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_culture', models.CharField(max_length=100)),
                ('date_plantation', models.DateField()),
                ('date_recolte_prevue', models.DateField()),
                ('etat_actuel', models.CharField(choices=[('semis', 'Semis'), ('croissance', 'Croissance'), ('recolte', 'Récolte')], max_length=100)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='Gestions.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestions.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('livrée', 'Livrée'), ('annulée', 'Annulée')], max_length=50)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='Gestions.membre')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestions.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='Gestions.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_question', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Gestions.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_reponse', models.CharField(max_length=200)),
                ('correcte', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='Gestions.question')),
            ],
        ),
        migrations.CreateModel(
            name='Tutoriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('fichier_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoriels', to='Gestions.formation')),
            ],
        ),
    ]
