# Generated by Django 5.1.1 on 2024-11-03 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestions', '0005_article_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_publication',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
