# Generated by Django 5.1.1 on 2024-11-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestions', '0006_article_date_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='notification_envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
