# Generated by Django 5.1.1 on 2024-11-05 00:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestions', '0007_article_notification_envoyee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriptionformation',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='inscriptionformation',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='tutoriel',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='formateur',
        ),
        migrations.AddField(
            model_name='formation',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='Gestions.membre'),
        ),
        migrations.AddField(
            model_name='formation',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='formation',
            name='quiz',
            field=models.TextField(blank=True, help_text='Ajoutez des questions de quiz pour autoformation', null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_formations/'),
        ),
        migrations.AddField(
            model_name='production',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_productions/'),
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='InscriptionFormation',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Reponse',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Tutoriel',
        ),
    ]
