# Generated by Django 5.1.1 on 2024-11-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestions', '0008_remove_inscriptionformation_formation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
                ('rendement', models.FloatField()),
                ('date_plantation', models.DateField()),
                ('date_recolte', models.DateField()),
                ('commentaires', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Production',
        ),
    ]
